ARM: dts: stm32: update dsi node in stm32mp15-no-scmi.dtsi
If building DT for STM32MP151 or STM32MP153 SoCs, the following
issue occurs:

  DTC     arch/arm/dts/stm32mp157d-ev1.dtb
Error: u-boot/arch/arm/dts/stm32mp15-no-scmi.dtsi:104.1-5 Label or path dsi not found
FATAL ERROR: Syntax error parsing input tree
scripts/Makefile.lib:308: recipe for target 'arch/arm/dts/stm32mp153a-as-fftp01-mx.dtb' failed
make[3]: *** [arch/arm/dts/stm32mp153a-as-fftp01-mx.dtb] Error 1
make[3]: *** Waiting for unfinished jobs....

To fix it, the addon for dsi clocks must be updated in
stm32mp15-no-scmi.dtsi as dsi node not defined STM32MP151 and
STM32MP153 SoCs.

Signed-off-by: Patrice Chotard <patrice.chotard@st.com>
Change-Id: I4f15316062f379d1694bb0688e0b7772e946fe9f
Reviewed-on: https://gerrit.st.com/c/mpu/oe/st/u-boot/+/175282
Reviewed-by: CITOOLS <smet-aci-reviews@lists.codex.cro.st.com>
Reviewed-by: CIBUILD <smet-aci-builds@lists.codex.cro.st.com>
Reviewed-by: Patrick DELAUNAY <patrick.delaunay@st.com>
Tested-by: Patrick DELAUNAY <patrick.delaunay@st.com>